### PR TITLE
Update syntax definitions in source.c.platform

### PR DESCRIPTION
**Pull request by patrickrgaffney**
This is a bit of an opinionated PR, but I think it could be useful.

Basically it replaces the scope definitions in `Platform.tmLanguage` with two new files:
- `CLib.tmLanguage`
- `POSIX.tmLanguage`

You can probably guess what definitions are in them. `CLib.tmLanguage` contains scopes for _all_ of the (external) variables, constants, types, and functions that are defined in the C standard (C11).  `POSIX.tmLanguage` does the same, except for all of the POSIX standard headers (POSIX.1-2008).

As far as the scopes go, I opted to go a different way than previously done in `Platform.tmLanguage`. Part of my reasoning for just starting over — instead of attempting to edit `Platform.tmLanguage` — had mostly to do with the giant mess of regex contained in that file. So in both the new files, each header is given up to 4 scopes — one for each type, constant, external variable, and function.

For example, the `<glob.h>` header defines a new type, two functions, and a set of constants to aid with those functions. This is represented in `POSIX.tmLanguage` as 3 new scopes:
- `support.constant.glob.c`: the constants
- `support.type.glob.c`: the type
- `support.function.glob.c`: the functions

The main advantage to doing it this way is it's _infinitely_ more editable later. If you put all the functions in CLib and/or POSIX into one regex it becomes a mess pretty quickly.  I didn't see any noticeable lag in the syntax highlighting either.

I added a file to the Support folder that contains all of the headers in both CLib and POSIX in alphabetic order laying out the types, variables, constants, and functions in each.  These were pulled from the C11 standard and the [POSIX.1-2008 standard](http://pubs.opengroup.org/onlinepubs/9699919799/).

---

It is hard to tell exactly what is defined in `Platform.tmLanguage`, but I first begin compiling these definitions when I would run into a CLib function that was not highlighting correctly. After awhile, I became so accustomed to having the library functions and constants highlighted that I decided to (slowly) go through and add the POSIX headers.  After spending an inscrutable amount of time searching and editing the Platform file, I just decided it was best to start from scratch.

Some care has been taken on my part to remove all of the duplication from `CLib` and `POSIX` — in other words, a lot of the headers end up defining the same types, and if this occurs, the more sensible header was chosen.

### CODE REVIEW

**Comment by sorbits** [comment]
> It is hard to tell exactly what is defined in `Platform.tmLanguage`

The file was generated using libclang. Basically parsing a dummy file and harvesting symbols from the AST, the dummy file was using the includes below, hence the symbols would be limited to what got defined or included by those files:

	#import <CoreFoundation/CoreFoundation.h>
	#import <MacTypes.h>
	#import <stdio.h>
	#import <stdint.h>
	#import <math.h>
	#import <pthread.h>
	#import <dispatch/dispatch.h>
	#import <unistd.h>
	#import <fcntl.h>

	// Cocoa
	#import <objc/runtime.h>

I never polished the system enough to publish it, but in light of your work, I will try to find time for doing that as soon as possible, and then add your headers to the file to see if we can continue with fully generated headers, since it’s easier to update these (mainly for updated platform SDKs).

**Comment by sorbits** [comment]
And sorry for not having a _“This file has been generated by X”_ comment in `Platform.tmLanguage`.

**Comment by sorbits** [comment]
Please have a look at https://github.com/textmate/objective-c.tmbundle/tree/master/Support/Platform

Note that I added `Platform.md` so that it’s easy to see what actual changes happens in `Platform.tmLanguage`.

**Comment by patrickrgaffney** [comment]
> The file was generated using libclang.

Ahh, that makes more sense. I was struggling to come to grips with how one person could create those regex by hand.

> And sorry for not having a *“This file has been generated by X”* comment in `Platform.tmLanguage`.

No worries.

> Please have a look at <https://github.com/textmate/objective-c.tmbundle/tree/master/Support/Platform>.

I will try and go through this in the next few days as I find time. I'm no Objective-C expert, but I'll see what can be done to make updating these grammars more programatic in the future.

> Note that I added `Platform.md` so that it’s easy to see what actual changes happens in `Platform.tmLanguage`.

This is great, thanks!

---

Now do you still want to dump all the grammar's into `Platform.tmLanguage`? I guess what I am saying is, are you opposed to having each platform or standard generate their own `.tmLanguage` grammar?  Going through your code quickly it would seem natural to split it into the following files:

- `POSIX.tmLanguage` -- POSIX standard header definitions
    - this could be included in the C, C++, Objective-C grammar
- `CLib.tmLanguage` -- CLib header definitions
    - this could be included in the C, C++, Objective-C grammar
    - this file could be combined with `POSIX.tmLanguage` as both would be included in all of the C-family of grammars
- `CppLib.tmLanguage` -- C++ header definitions
    - this could be included in the C++, Objective-C grammar
- `Foundation.tmLanguage` -- Cocoa defintions
    - to be included in the Objective-C grammar

Maybe this makes sense, maybe it makes more sense to keep it all in one file.  Let me know what you think.

**Comment by sorbits** [comment]
> Now do you still want to dump all the grammar's into `Platform.tmLanguage`?

I have no problem splitting it up, but for _Foundation_ we may want something like _macOS_ because there are several Apple frameworks that we recognize.

**Comment by patrickrgaffney** [comment]
Sorry, this got pushed to the bottom of the todo list.

I couldn't get the [generator](https://github.com/textmate/objective-c.tmbundle/blob/master/Support/Platform/generator.mm) to compile. This motivated me write a little python script — using the [clang library](https://pypi.python.org/pypi/clang) — to parse the AST. It was sloppy, but it mostly worked. 

I kept running into the same few issues:

- The parser finishes the preprocessing stage before emitting the tree, so anything in the libraries defined as a macro/constant/etc is lost by the time I get it.
- Parsing the headers on macOS seemed to give me a lot of Darwin-specific items, i.e: things not defined by the C standard or by POSIX.

These aren't huge deals, but they present problems I don't really want to solve.

I agree that generating the file with a script is *way* easier than by hand or by scraping the POSIX site, but it's complete now — and the C/POSIX standards don't change very often. 😎 Trying to keep up with the changes for Foundation would be considerably harder (and probably should be automated).

I originally compiled all those types/external vars/constants/functions because I wanted *smart* highlighting on the things defined in the C libraries.  That portion of this is complete now, and I am mostly happy with it (I use these grammars everyday).

**Comment by sorbits** [comment]
OK, I’ll close the PR.

I updated `Platform.tmLanguage` for C and Objective-C using the 10.12 SDK.

**Pull request closed without merging**
